### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by sohilpandya** [sohilpandya/katasohil#1]
I'm having a problem with this.

**Comment by IonicaBizau** [comment]
@sohilpandya Check my answer, hope it brings some light: http://stackoverflow.com/a/33394386/1420197 :joy:

**Comment by sohilpandya** [comment]
Thanks @IonicaBizau where would the scope be added? in the first post request we make to obtain the token or with the second post request we are making to actually create the issue?

for e.g. `'/repos/sohilpandya/katasohil/issues?client_id=###&scope=user,public,repo'`

**Comment by sohilpandya** [comment]
it is strange that when making this request in apigee I am not having to add these scopes and it seems to work ok

**Comment by IonicaBizau** [comment]
@sohilpandya Are you using OAuth? You should have an url looking like `https://github.com/login/oauth/authorize?client_id=<client-id>&scope=public_repo&redirect_uri=<redirect-uri>` :dizzy:
